Vagrant.configure("2") do |config|
  
  config.vm.provider "libvirt" do |lv|
    lv.memory = 4000
    lv.cpus = 2
  end

  config.vm.define "controller" do |ctrl|
    ctrl.vm.box = "ubuntu/jammy64"
    ctrl.vm.hostname = "ansible-controller"
    ctrl.vm.network "private_network", ip: "192.168.56.3"
  end

  config.vm.define "windows" do |win|
    win.vm.box = "valengus/windows11-22h2-x64"
    win.vm.hostname = "windows-node"
    win.vm.network "private_network", ip: "192.168.56.4"
  end
  
end
